# Generated by Django 3.0.5 on 2020-04-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransfer',
            name='amount',
            field=models.FloatField(),
        ),
    ]
