# Generated by Django 3.0.5 on 2020-04-15 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_deposit_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='account',
        ),
    ]
