# Generated by Django 3.0.5 on 2020-04-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.PositiveIntegerField()),
                ('mobile_number', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tbl_Customers',
            },
        ),
    ]
